### ISSUE TITLE
创建数据库时出现问题

### ISSUE THREAD

**Issue by Iridescent-9** [Eslzzyl/OnlineLibrary#1]
在执行
```
 dotnet ef database update
```
时有如下错误
![image](https://github.com/Eslzzyl/OnlineLibrary/assets/61072544/7d1ce91c-d0e7-4f67-ad39-35b8bbd969e7)

NuGet包应该是恢复全了
![image](https://github.com/Eslzzyl/OnlineLibrary/assets/61072544/24a3ff04-423d-4668-8c7b-bca2eba6dc3b)

**Comment by Eslzzyl** [comment]
你好，
这是因为项目中有两个 `DbContext`，而在执行 `database update` 时没有指定具体的 `DbContext`。我在加入第二个 `DbContext` 后没有及时更新文档。你可以执行
```
dotnet ef database update --context ApplicationDbContext
```
来更新数据库。

**Comment by Iridescent-9** [comment]
好嘞，我再试试
